"""Methods exposed by the authenticated worker RPC endpoint."""

WORKER_METHODS = {
    "planner_context",
    "learning_claim",
    "learning_finish",
    "skills_publish",
    "get_job",
    "update_job",
    "event",
    "lease",
    "claim",
    "check",
    "transfer",
    "boundary",
    "proposal",
    "authorize_operation",
    "approvals",
    "stale_approval",
    "begin_action",
    "begin_window_recovery",
    "finish_window_recovery",
    "finish_action",
    "result",
    "search_knowledge",
    "conversation",
    "ask_staff",
    "bind_record",
    "report_capability_gap",
    "conclude",
    "package_access",
}
